apiVersion: v1
kind: Service
metadata:
  name: erlang-docker-b-hl
  namespace: default
  labels:
    app: erlang-docker-b
spec:
  clusterIP: None
  selector:
    app: erlang-docker-b
  ports:
    - port: 80              # 用于 service 访问时用
      targetPort: 8080      # 对应 `pod` 中程序的端口, 这里是 erlang 节点的 http 端口
